### ISSUE TITLE
better openshift guide

### ISSUE THREAD

**Issue by danielpetrica** [huginn/huginn#1388]
Hi is someone using it on openshift? If yes could you please provide a easy set-up guide?

**Comment by cantino** [comment]
I haven't tried it in quite a while.  We have https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-OpenShift, but I don't know if it still works.

**Comment by somepaulo** [comment]
Doesn't seem like...

**Comment by cantino** [comment]
Can OpenShift run Docker?

**Comment by MatElGran** [comment]
Hi, 

Commenting here thanks to codetriage.com. 

This issue seems like it could be closed, given the PR submitted above has been merged.

@danielpetrica, what do you think ?

To maintainers, first thanks for your time and dedication, and please do not hesitate to tell me if this not the correct way to do this, or if this is not wished for
