### ISSUE TITLE
Getting "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by Sowad** [huginn/huginn#2151]
I'm on Ubuntu 16.04 on digitalocean 512mb ram vps (which is only supposed to run huginn). I followed https://github.com/huginn/huginn/blob/master/doc/manual/installation.md and did everything. And now after going to my server's ip I'm getting 

> _**We're sorry, but something went wrong.**_

**Comment by virtadpt** [comment]
We need more information to go on.  What does Rails return?  What does the process worker return?  anything in the log files?  What about the Nginx logs?  That's not enough to troubleshoot from.

**Comment by Sowad** [comment]
The status check shows its running and here are the logs https://gist.github.com/Sowad/02a6dd5348aec83f27239a2f69c53d3d

**Comment by dsander** [comment]
You seem to have multiple problems, which all might be cause by the server running out of memory:
```
E, [2017-10-23T15:34:14.315349 #32466] ERROR -- : Cannot allocate memory - fork(2) (Errno::ENOMEM)
```
Did you configure a swap partition on your server? You need at least 512MB, 1GB might be better https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

After you configured the swap try restarting the server, if you still get errors afterwards please post the logs again (we only need the last few dozen-hundred lines).

**Comment by Sowad** [comment]
Still same thing
Here are the logs (smaller) 
https://gist.github.com/Sowad/aea50689cfd27456f27e79c21bb8c386

**Comment by dsander** [comment]
It looks like the assets are not precompiled:
```
ActionView::Template::Error (The asset "odin.jpg" is not present in the asset pipeline.):
```

It is possible the command failed because the server ran out of memory when you executed it the first time. Try first stopping everything with `sudo bundle exec rake production:stop` and then [run the precompilation](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#compile-assets) again. Afterwards you need to start the services with `sudo bundle exec rake production:start`

**Comment by Sowad** [comment]
Thanks worked!
