### ISSUE TITLE
WebsiteAgent marked "Not working" but can't figure out why

### ISSUE THREAD

**Issue by a10kiloham** [huginn/huginn#2173]
I found a few prior threads but no sign of what the cause is here:

WebsiteAgent, working as expected results-wise. Events log totally clean. Time well within the last-expected time.

I've got a few website agents doing this, no rhyme or reason, as many others work as expected. Any further ideas?

**Comment by dsander** [comment]
When did the WebsiteAgent create it's last event? The working method is checking for the time when it last created an Event, not when it last received one.

The screenshot you shared is a `EmailDigestAgent` it's working method is only checking if the the error log is empty or if it received a event successfully since the last error happened.

**Comment by bobbysteel** [comment]
Here's a better screenshot. This has been going for a long time, gets results every 2 hours usually and still shows not working. No errors easily visible in logs either :/
https://imgur.com/a/MniSs

**Comment by dsander** [comment]
Did you check the Agents log? If it logged an error after it created the last Event it will be shown as not working.

**Comment by bobbysteel** [comment]
you mean the log linked to on the left hand side of the agent view? yes,
there's no visible error anywhere in that first page at least.

**Comment by dsander** [comment]
The working check is based on the `last_event_at` and `last_error_log_at` database columns of the agents table, can you check those?

**Comment by bobbysteel** [comment]
Last event was an hour ago but looks like there was some error 6 hours
previously. why wouldn't a more recent last_event_at clear the is_working
flag?

**Comment by dsander** [comment]
Did you check those values at the database level? It might be possible that the event was created but the Agent row from the `agents` table was not properly updated.

**Comment by bobbysteel** [comment]
Yes the database shows the last error about 6 hours before. Should the
logic clear errors if agents run properly afterwards?

**Comment by dsander** [comment]
The working logic for the WebsiteAgent is the following:
```ruby
  def working?
      event_created_within?(options['expected_update_period_in_days']) && !recent_error_logs?
    end
  def recent_error_logs?
    last_event_at && last_error_log_at && last_error_log_at > (last_event_at - 2.minutes)
  end
```
From what you have described the Agent should be shown as working. Do you know how to get into a Rails console of your production server? It would be interesting what the individual parts of the logic return:
```
a = Agent.find(<your agent id>)
a.event_created_within?(4)
a.recent_error_logs?
```

**Comment by bobbysteel** [comment]
i can get into bash on the docker image. how can i enter the console from
there, and do i just paste those lines?

**Comment by dsander** [comment]
When you are inside the docker container those command should get you a rails console:
```bash
cd /app
source .env
bundle exec rails c
```

**Comment by bobbysteel** [comment]
Running that code returns true and true.
```
irb(main):002:0> a.event_created_within?(4)
=> true
irb(main):003:0> a.recent_error_logs?
=> true
irb(main):005:0> a.last_error_log_at?
=> true
irb(main):006:0> a.last_error_log_at
=> Mon, 18 Dec 2017 12:03:38 GMT +00:00
irb(main):007:0> a.last_event_at
=> Mon, 18 Dec 2017 12:04:22 GMT +00:00
```

I can't recall how to access logs though as the docker image seems to just drop them. This agent returns about 500 events on each run, so what's happening seems to be one error out of the 500 being thrown, so the Agent is being constantly marked as not working... FWIW, it would be nice if the in-app event viewer had a way to filter for errors since big agents like this scroll them out of the buffer rather quickly (or at least pagination to go back further)
Cheers

**Comment by dsander** [comment]
The Agent is logging those kind of errors in it's own log (the `Log` button on the right side of the Agents show page), but you are right especially with "nosy" Agents like the `WebsiteAgent` it can be a bit daunting to slip through the pages to find the error.
