### ISSUE TITLE
LiquidOutputAgent: response_headers option missing

### ISSUE THREAD

**Issue by mightymt** [huginn/huginn#2513]
According to the LiquidOutputAgent's documentation there should be a "response_headers" option. However when I create such agent this option is missing (see Screenshot below).

This screenshot is from a new installation I just created using the "Depoloy to Heroku" button.

Has this option be deprecated/removed or is it missing due to a limitation on Heroku's servers? 
How I can set the "Access-Control-Allow-Origin" header for the LiquidOutputAgent?

![2019-03-28 09_00_06-Window](https://user-images.githubusercontent.com/4930561/55141005-b00ae300-5139-11e9-9a80-35b616fac567.png)

**Comment by dsander** [comment]
In theory the Agent supports those options, but when the feature was added, we forgot to add it to the configuration (the main target for the feature was the DataOutputAgent). The problem is that Agents which are configurable via normal HTML forms can not support "dynamic" options like arrays or objects.

The quick solution would be to remove the form configurable option from the LiquidOutputAgent, but that would make configuring the content really annoying.

**Comment by mightymt** [comment]
Ok, thanks for the quick reply. I understand now what the issue is.

In my case I can't use the DataOutputAgent because I need to output the data in GeoJSON format.

So if I were to remove (or comment out) line 3 and lines 103-108 in liquid_output_agent.rb would it fall back to the default editor?

**Comment by dsander** [comment]
Yes, I think that should work.

**Comment by mightymt** [comment]
Just wanted to say, that I tried what I mentioned above. It works fine for my specific use case, even though it's not a perfect solution.
