### ISSUE TITLE
adding random option for daily scheduling

### ISSUE THREAD

**Issue by hihouhou** [huginn/huginn#2549]
Hello,

I have 133 agents actually and more than 60 for daily check. Is it possible adding random option for daily check ? 60 checks are scheduling at the same time. It should be cool to be reparted better in the daily.

Regards,

**Comment by dsander** [comment]
Hi,

there isn't an easy way to do this. Even if we would introduce randomness to the scheduler, the same offset would be applied to all Agents configured to be run at the selected schedule. This is because the scheduler works "per schedule", i.e. it runs during the preconfigured times and runs all Agents that have the current schedule selected.

You could manually spread the Agents over a few hours by selecting different schedules or use a `SchedulerAgent` if you need finer control over the time.

**Comment by hihouhou** [comment]
OK thank you 👍
