### ISSUE TITLE
How to convert an image link to base64 in huginn?

### ISSUE THREAD

**Issue by sqliuchang** [huginn/huginn#2680]
I made a scenario to generate a RSS feed from a forum's newest posts. But the images of these posts require cookie to load.
I can view them in the website of TT-RSS when I use Chrome on PC because I have logged in. But when I use an Android app to read RSS feeds, the images can't be downloaded.
So I want to know if there is a way to convert an image link to base64 to save these blocked images.

**Comment by dsander** [comment]
Hmm, I don't think there is a way to do this with the build in Agents. The problem is that we don't have Agents that can download and process files while still keeping the normal "event flow". I am sure you could do it with a custom script and the `ShellCommandAgent` or by writing an Agent gem in ruby.

With almost only "plain" Huginn you could extract the image URLs, download them via `wget` and a `ShellCommandAgent` while replacing the URL with the one where you put the downloaded file.

**Comment by sqliuchang** [comment]
> With almost only "plain" Huginn you could extract the image URLs, download them via `wget` and a `ShellCommandAgent` while replacing the URL with the one where you put the downloaded file.

Got it, thank you!
