### ISSUE TITLE
Please help with website agent

### ISSUE THREAD

**Issue by mmm286** [huginn/huginn#2776]
Hi,
I'm newbie with these application. First of all, congratulations for your wonderfoul world.
I'm trying to scrape with website agent but it seems not works. 
My code is:

```
{
  "expected_update_period_in_days": "2",
  "url": "https://es.wallapop.com/search?distance=100000&time_filter=lastWeek&keywords=%22pantalon%22%20NOT%20%22iphone%208%22%20NOT%20%22Apple%20watch%22%20NOT%20%22samsung%22%20%20NOT%20%22huawei%22%20&min_sale_price=5&max_sale_price=100&order_by=newest&latitude=40.39676&longitude=-3.636",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "desc": {
      "xpath": "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"product-info-title\", \" \" ))]",
      "value": "\".//text()\""
    },
    "titulo": {
      "css": ".product-info-title",
      "value": ".//text()"
    }
  }
}
```

I'm tring to get css and xpath with selectogadget but it seems not works. Could you help me please?
Thanks and sorry for my English!

**Comment by dsander** [comment]
Hi!

You picked a very difficult first website 😄 It is using JavaScript to generate the content. Huginn itself is not able to scrape pages build via Javascript, but you can use [fulldom-server](https://github.com/strugee/fulldom-server) or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the JavaScript.

If you open the developer tools of your browser you can see the requests the website makes in the network tab. Looking at the request headers it is sending I was able to get back some data using this `WebsiteAgent` configuration. Because of the `timestamp` header I am assuming that the request will only work for a limited amount of time:

```json
{
  "expected_update_period_in_days": "2",
  "url": "https://api.wallapop.com/api/v3/general/search?distance=100000&time_filter=lastWeek&keywords=%22pantalon%22+NOT+%22iphone+8%22+NOT+%22Apple+watch%22+NOT+%22samsung%22++NOT+%22huawei%22+&min_sale_price=5&max_sale_price=100&order_by=newest&latitude=40.4893538&longitude=-3.6827461&filters_source=quick_filters&language=es_ES",
  "type": "json",
  "mode": "on_change",
  "headers": {
    "X-Signature": "oyQbrF4XBHg40wQdzJytES6thC9z2z+rvs+KQpcIn8M=",
    "Timestamp": "1589063737703"
  }
}
```

**Comment by mmm286** [comment]
Many thanks for your answer, you are a guru!!!
