### ISSUE TITLE
How to debug Ruby foreman project?

### ISSUE THREAD

**Issue by mozgbrasil** [huginn/huginn#2857]
If you can help

-

As per images

https://drive.google.com/file/d/1GvQfJhf8WSbvIKecCLCpKcN3hglqs0pQ/view?usp=sharing

I created in the workspace some releases

The IDE starts the application, until I show the return in chrome

The problem is that the variable pointed at the breakpoint is not being returned

Can anyone help?

-

As per images

https://drive.google.com/file/d/1M6mhdvItbj2cu0Zqool6D5VZzhJHpM72/view?usp=sharing

The IDE starts the application, until I show the return in chrome

The problem is that the error is being returned when trying to debug the application

Can anyone help?

-

**Comment by dsander** [comment]
Sorry I have not really a solution because I have never used the vscode debugger with a ruby process. It might work if you start the process you want to debug via vscode directly. Remove the process from the `Procfile`, start foreman in a console and add the process you want to debug to the vscode launch configuration.

**Comment by mozgbrasil** [comment]
Good afternoon my friend

You are the best, thank you very much

![Captura de tela de 2020-08-11 14-46-23](https://user-images.githubusercontent.com/17202780/89930750-9ad50e00-dbe1-11ea-9a0c-ebf1707d44e6.png)

**Comment by pdf3rn** [comment]
Hi @mozgbrasil , Can you share the configuration you used in your launch.js to make this work?
