### ISSUE TITLE
Noob question "heroku config:set AGENT_LOG_LENGTH=20"

### ISSUE THREAD

**Issue by robotfx** [huginn/huginn#2862]
So I know I should run this command to set a limit to the logs, if I'm using the heroku's free plan. But where exactly do I have to do it?
Every time I do it in online, from the dashboard's console, I get a 'heroku: command not found' message, so I'm guessing nothing happens. Is there another way to set this limit?
![3973c2bf-f7d9-480c-8b6d-5b4b3bbd391c](https://user-images.githubusercontent.com/46458914/90954035-bdc8b300-e468-11ea-85d8-668c3f5ddeb4.png)

**Comment by dsander** [comment]
Sorry I have no idea what the Dashboard console is. I normally have the Heroku CLI utility installed on my machine locally. I believe you can also assign environment variables to applications using the Heroku web interface. You need to restart the application after changing any variable so that they are applied.

**Comment by robotfx** [comment]
Thanks, I've just found out that I can just add this in the Settings > Config Vars, without the need of the command prompt.
