### ISSUE TITLE
CertificateFailureError

### ISSUE THREAD

**Issue by BlueCog** [huginn/huginn#3030]
I'm getting an certificate errors (using openshift template)

`Retrying fetcher due to error (2/3): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.` 

This is probably due the existence of a proxy server / missing ca certs in my environment. Is it possible to set a custom ruby image?

**Comment by paul-sx** [comment]
If you are using a proxy server with MitM certificates you need to add the root certs for rubygems.  [This guide](https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#installing-new-rubygems-certificates) has instructions on where to put the MitM root certificates so that Ruby is ok with it.
