### ISSUE TITLE
<abbr> tag handling - can't extract href

### ISSUE THREAD

**Issue by Linecutterx** [huginn/huginn#3086]
WebsiteAgent:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.edcforums.com/find-new/199140153/posts",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "ThatUrl": {
      "css": ".lastPostInfo .muted a",
      "value": "."
    }
  }
}
```
Should show the html here (href part is the important bit):
```
<a href="posts/2731648/" title="Go to last message" class="dateTime">
				
					<abbr class="DateTime" data-time="1644858457" data-diff="10501" data-datestring="Feb 14, 2022" data-timestring="5:07 PM" title="Feb 14, 2022 at 5:07 PM">Today at 5:07 PM</abbr>
				
				</a>
```

However it returns:
```
{
    "ThatUrl": "<a class=\"dateTime\">\n\t\t\t\t\n\t\t\t\t\t<abbr class=\"DateTime\" data-time=\"1644858457\" data-diff=\"10733\" data-datestring=\"Feb 14, 2022\" data-timestring=\"11:07 AM\">Feb 14, 2022 at 11:07 AM</abbr>\n\t\t\t\t\n\t\t\t\t</a>"
  }
```

Same result whether you use ".", "string(.)", "./node()"

Seems that the <abbr> tag is preventing the inner html from being read by the agent.

**Comment by gingerbeardman** [comment]
You want to use `"value": "@href"`

**Comment by Linecutterx** [comment]
> You want to use `"value": "@href"` to get the href attribute of the anchor link you're targeting.

Are you sure???
```
{
    "ThatUrl": ""
  }
```

You'll note that dumping the html (as shown before) doesn't return the href that is actually there in the <a></a> section. You can change the @href to @title & get the same result. Likewise if you change the css selector to ".lastPostInfo .muted .dateTime"
The tabs-newline-tabs part is inherited from css from elsewhere (I think)

**Comment by gingerbeardman** [comment]
I'm positive that @href should get you the link if everything is as it should be.

But, I think I see the problem...

When testing I could not find the exact structure of HTML that you quote above, because I'm not a member of the forum and I'm not logged in. I would guess that Huginn is also not logged in when doing this request?

So you either need to find the links you want on a page that is not logged in (which I guess is not possible) or find a way to login when using Huginn, maybe browserless will be able to do it?

Let me know if this helps!

**Comment by gingerbeardman** [comment]
Example flow of how to log in: https://github.com/huginn/huginn/issues/2575#issuecomment-517910943
