### ISSUE TITLE
Better handling of situation when there is no network

### ISSUE THREAD

**Issue by gingerbeardman** [huginn/huginn#3092]
We had a power cut recently and network was offline for some time.

When it came back on Huginn had a massive queue of events.

I retried them all manually, but it got me thinking that maybe there could be an option to not que further events if the queue is not moving? or some other way to better deal with the situation than stacking events?

**Comment by qay21** [comment]
Hi,

I'm currently investigating a problem of job stacking without obvious causes. We had this problem in the past, then didn't have it anymore, and now having it again, on a very frequent basis. Fix is easy : "Remove all jobs" in the queue (but this mean some required jobs also have to be re-queued manually).

Huginn doesn't seem to be overwhelmed, when looking at CPU/RAM/IO usage. And yet, jobs are stacking to 1000s and 1000s of queued jobs. When looking at our dashboards, I can't see any network disconnection, but I can see a noticeable spike in network activity (despite no expected change in jobs load) correlated with a spike in context switchs.

Could this indicate a very short network problem, causing Huginn to not being able to properly finish each task and so stacking jobs in the queue ?

**Comment by virtadpt** [comment]
It could be.

Which job workers (threaded or delayed_job) are you using, and how many?  Is the job scheduler healthy?

**Comment by qay21** [comment]
AFAIK we are using the official docker image, without splitting processes in separate containers. The only "performance" related parameter we edited is the DATABASE_POOL set to 30 (instead of the default 20 if I recall correctly).

So far we haven't had the need to increase the number of workers, so I'm not very familiar with Huginn's internal structure. But our workload has been consistently growing over the last year. Does this mean workers can be overwhelmed without showing that much on RAM/CPU usage ?

And if yes, would you recommend to split our monolithic install to a better informed architecture with separate containers for more workers of each type ? This is absolutely something our team is capable of, we simply didn't explore these options yet.

**Comment by virtadpt** [comment]
Okay, that sounds like the multiprocess Docker image.

Upping the size of the connection pool makes sense.

It is not necessarily accurate to say that the workers can be overwhelmed, because that implies that the tasks are CPU bound, network bound, or some combination of both.  It is probably more accurate to say that, as the number of scheduled agent executions increases, the bottleneck lies in the number of job workers that can pick them out of the queue.  To put it another way, if there are 10 jobs to run at the same time (that are not dependent upon one another), but only three job workers in the system, some of those jobs are going to have to wait their turn.

I've seen this happen in my setup (though I don't use Docker) and what I had to do was spin up more delayed_job instances to pick up the slack.  So, you'll want to investigate the [single process per container, but multiple containers](https://github.com/huginn/huginn/blob/master/docker/single-process/README.md) Docker image.  I recommend against using `bin/threaded.rb` because it [uses a GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock) so you're effectively getting only one thread running at any single time.  I would strongly recommend going with slightly modified containers that use `script/delayed_job` instead (they run only one job at a time, but you can have as many running as you have database connections), stand up a pack of them (you have 30 database connections available, so start with 20 or 25, and leave a few connections free for Rails, `bin/schedule.rb`, and maybe some overhead just in case) and see how it responds.

**Comment by qay21** [comment]
Wow that is a great answer, thanks a lot @virtadpt ! We are definitely going to scale up our install and see for adding some workers.

**Comment by gingerbeardman** [comment]
How did I know that this notification was going to be for an issues that's still a problem being closed.

What a fricking waste of time.
