### ISSUE TITLE
Data Output Agent with zero items shown as "working: no"

### ISSUE THREAD

**Issue by gingerbeardman** [huginn/huginn#3164]
From: https://github.com/huginn/huginn/issues/3034

Data Output Agent with zero items shown as "working: no". 

I think these two outcomes should be distinct:

1. working but with zero events
2. not working for any other reason

Some of my agents return results infrequently, maybe once a month, meanwhile it's misleading to see the red badge "working: no".

**Comment by virtadpt** [comment]
This has been a thing for years.  I still don't understand why.

**Comment by gingerbeardman** [comment]
yes, it's very odd. it has bothered me since day one but yesterday I was looking at some related issues in #3304 and figured I would do something about it!

https://github.com/huginn/huginn/blob/4df1217d3055db980a04f293e28016b77826e3ca/app/models/agents/data_output_agent.rb#L86-L88

For it to be marked as working it requires some results, but IMHO that's an incorrect assumption about whether it is working or not.

**Comment by Unending** [comment]
Consider interpreting `Working: No` not as in exclusively broken but also as not doing anything, not processing, unemployed. It isn't always an indication that something is wrong with the agent itself but perhaps something upstream.
This is why the `expected_update/receive_period_in_days` is a thing. You expected an event but it has been too long, that might be a problem.

If you expect infrequent events adjust this parameter accordingly. Yes that does end in setting it to something stupid-high in certain cases.

Splitting these up would be a quality of life improvement.
Error handling could do with a major retooling in general though. I have agents that say `Working: No` because a website wasn't reachable for five minutes three months ago, and others that have such a high throughput/log creation that any errors roll over before I ever see them and always say `Working: Yes`.

**Comment by gingerbeardman** [comment]
FFS not stale
