### ISSUE TITLE
Javascript Agent: How access Key/Value Agent (controller agent) memory?

### ISSUE THREAD

**Issue by andreabonanno** [huginn/huginn#3271]
As I'm implementing some custom logic within a JS Agent, I need to access key/value pairs stored with a Key/Value Store Agent.
This agent is set to be the Controller for the JS Agent. 
Also, could someone provide an example how the Store Agent memory should be parsed in the JS code?

Thanks for the help!

**Comment by Plausible0Bug** [comment]
try accesing `event.agent.memory` after you set JavaScript agent as the controller of key value store agent?
Not tested, use at your own risk.

**Comment by knu** [comment]
This was a missing piece.  JavaScriptAgent should have access to storage provided by KeyValueStoreAgents.

**Comment by tortoo** [comment]
The JavaScript Agent still seems to be unable to fully access the memory of Key Value Store Agent. Currently it can only be called through this.createEvent() rather than this.log(). 

For example, `var abc = this.kvs` While `this.log(abc)` always outputs nothing. Hope `this.kvs` can be accessed globally like `this.credential()`. #3333
