### ISSUE TITLE
Same agent, different scheduling for different scenarios?

### ISSUE THREAD

**Issue by killermouse0** [huginn/huginn#3312]
I would like to be able to run the same agent on two different schedules for the purpose of two different scenarios.

For example: 
- at 9am I want to retrieve a stock price to send this in a morning edition email digest
- every 5 minutes between 9 and 6pm I want to retrieve that same stock price (therefore running the same agent) but this time detect a wild variation and send a notification to my phone

At the moment, I think I need to clone the stock price retrieval and make it two different agents, because the scheduling is part of the agent setup

Is there an elegant way to implement that double scheduling?

I'm a Huginn noob, so please forgive me if there's a canonical way to do this sort of things that I missed!

Thanks for any hint!

**Comment by virtadpt** [comment]
Best practice would be to clone the stock price agent, and have one copy in each scenario.  It would also be easier because the agent would be emitting events to two separate chains of agents; with a single copy of the agent every connected agent would get the same events, and probably trigger at the same time.  You don't want that because you'll get spurious events constantly.

However, to do it the way you're thinking, you could do it with a couple of Scheduler Agents.  You could use one to execute the stock price agent every five minutes between 0900 and 1800 (`*/5 8-18 * * 1-5`).  Have your e-mail digest agent run at, say, 0901 with another Scheduler Agent (which gives the event time to propagate).  The agent network that does the statistical analysis (spike detection, et al) could just run whenever an event hits.

**Comment by killermouse0** [comment]
@virtadpt very clear, thank you for your help!
