### ISSUE TITLE
The future of Huginn

### ISSUE THREAD

**Issue by cantino** [huginn/huginn#34]
# Next Steps

I want to explore the next steps for Huginn and to talk about something much more ambitious than the current implementation.
### Huginn, the Protocol

Goals:
- Huginn Agents shouldn't have to be implemented in Ruby inside of a Rails app.  Agents should be implementable in any language.
- You should be able to interact with both local and remote Agents in the same way, with the same API.
- The system should be fast enough to tackle a wide variety of problems.

Proposal:
- Agents can be written in any language on any platform that can open persistent connections.
- Agents create and consume JSON Event objects.
- To consume events from an Agent you connect to that Agent's IP address and port and subscribe to a standing query for matching events.  The default query is something like `subscribe to *`, returning all generated events, but specific Agents can allow for more complex predicates, such as `subscribe where zipcode = 12345` (syntax TBD).
  - This could easily be wrapped in WebSockets.
  - This predicate language should be standardized and, importantly, very simple to implement.
  - It's possible that Agents should create events in a rolling event log and allow for short-term event replay from a specific timestamp so that a re-connecting Agent can recover any lost events.
- Agent configuration is not part of the spec.  Some Agents may be configured via the command line, others via a web GUI, still others can be paid remote services.
  - The reference implementation will make it easy to customize and deploy Agents on your own system with configuration via a web GUI similar to the current system.
  - The reference implementation may allow Agents to be sandboxed (a la [docker](http://www.docker.io/)) so that you can install semi-trusted 3rd-party code.
- Agents should be runnable locally or remotely.  The goal is to allow you to maintain control of your data by running everything locally, or to subscribe to remote Agents and participate in a larger data ecosystem.  Some questions:
  - How should local Agents be packaged and distributed?
  - What would a marketplace look like where you could easily subscribe to, or download and run, Agents for any purpose?
# What do you think?
### Get Involved!

Want to help create the future of Huginn?  Get involved!  You can comment and contribute here, send pull requests, follow [@tectonic](https://twitter.com/tectonic) on Twitter, or contact me directly on [my personal site](http://andrewcantino.com/) to discuss further involvement.

**Comment by alrik11es** [comment]
If you do not mind I would like to revive this thread to talk a little about the possibilities of integrating other programming languages ​​in Huginn.

I think the best bet is to create an interface that somehow allows those languages ​​to communicate with Huginn.

It can be approached in different ways, for example one option would be to create a small GUI that allows creating files that will later become agents. And these files once saved will be executed by the interpreter of the selected language.

For example, the language that I'm used to PHP only requires to have one of the versions installed on the server.

Once this file is created let's suppose that the list of agents that appears when creating a new agent is able to find this file and in some way Huginn is able to execute the interpreter and execute the first method that would be for the creation of the GUI of the agent. Suppose that it returns an XML/HTML that Huginn is able to reinterpret and create the fields.

Once viewing the GUI of the specified agent we would see fields and configurations defined.

I've created a simple example class in PHP that creates a simple Telegram Agent. As you can see Huginn should interface with this class in order to pass `$options` variable and the `$event`.

```php
<?php
namespace App\Agents;

use App\AgentInterface;
use \React\EventLoop\Factory;
use \unreal4u\TelegramAPI\HttpClientRequestHandler;
use \unreal4u\TelegramAPI\TgLog;
use \unreal4u\TelegramAPI\Telegram\Methods\SendMessage;

class Telegram implements AgentInterface
{
    public $name = 'Telegram agent';
    public $description = 'The Telegram Agent receives and collects events and sends them via Telegram.';

    public function process($options, $event)
    {
        $loop = Factory::create();
        $tgLog = new TgLog($options->token, new HttpClientRequestHandler($loop));
        $sendMessage = new SendMessage();
        $sendMessage->chat_id = $options->chat_id;
        $sendMessage->text = $event->text;
        $tgLog->performApiRequest($sendMessage);
        $loop->run();
    }

    public function gui()
    {
        return '
        <input name="token" type="text">
        <input name="chat_id" type="text">
        ';
    }
}
```
IF the direct interfacing possibility is not possible then we can define a communications protocol to ensure this works via API or something like that.

What do you think?

**Comment by 0xdevalias** [comment]
Not sure if I’ve mentioned it here before, but these days a lot of my thought process has tended more towards AWS lambda and similar ‘serverless’ technologies in place of what huginn would have solved for me in the past.

One ‘run it yourself’ serverless tech that would marry well with this concept of ‘agents in any language’ is OpenFaaS ( https://github.com/openfaas/faas )

While i’m sure you could approximate an integration with the web agent, I think a more directly supported bridge/maybe even some howto could be a really powerful addition to opening up huginn to a much larger pool of potential agents.

I feel like huginn has the ‘workflow’ and UI angle down pretty solidly, where OpenFaaS/Lambda/etc could provide nicer agent plugin potentials.

**Comment by alrik11es** [comment]
Could be that a solution for someone with a simple huginn server on a 3€/month VPS like me?

Don't know if we are using huginn the same way but at least for me the most condensed solutions on one location the best for me. Spreading all my flux through other platforms are a possibility but also adds another mesh of costs and complexity. My server with Huginn is always dancing free of load and could be doing this work.

While I agree with you I feel that I need this on huginn to be flexible enough to become a finished product with full potential.

In fact you gave me an Idea of making a simple platform that collects events from huggin over web or shell and process them using just functions that are defined by the user but as I said I prefer this to be integrated in huginn and not as a different application.

**Comment by virtadpt** [comment]
What about extending the Scheduler and Agent registry inside Huginn (I don't know what else to call the subsystem where Huginn keeps a list of the Agent types it supports) so that a user could upload custom agents that they wrote in other languages (PHP, Python, shell scripts, etc), tell Huginn that they exist (so that, when setting up a new Agent they're available as options), and run them with all the others.

An interface would need to be defined to pass events to those user-defined agents in the same way that they are to the internal ones, and an interface would need to be defined to pass events from those user-defined agents to everything else.

Heck, I'd kick some money in on Bountysource for this kind of functionality now that I think about it a little.  Can we crowdfund features on Bountysource?

**Comment by alrik11es** [comment]
This is definitely the most desirable option. Don't know if possible without a major refactoring, shame on me that I'm not a Ruby developer.

But meanwhile and slowly unless a solution for this need happens I'm creating a port of Huginn in Laravel for PHP, intending to have all this requirements in mind.

**Comment by dsander** [comment]
> IF the direct interfacing possibility is not possible then we can define a communications protocol to ensure this works via API or something like that.

We have the `ShellCommandAgent` which can execute any command that is installed on the Huginn server (granted that only really works when Huginn is not installed using docker). The fact that the needed interpreter would need to be present limits the potential. I don't see us adding every interpreter on the planet to the docker image ontop of that dependency management for the other languages could be annoying.



> I feel like huginn has the ‘workflow’ and UI angle down pretty solidly, where OpenFaaS/Lambda/etc could provide nicer agent plugin potentials.

I think I agree, `OpenFasS` and co are nice because they already have packaging and deployment figured out.

I believe the universal way to interact with other languages would be some sort of HTTP interface. It might be possible to have an Agent in Huginn that once the endpoint is configured shows the Agent description, validates the options and runs the Agent by making HTTP calls to the "agent server" that is written in a different language and is deployed somewhere (docker, locally, openfass, labda).

**Comment by alrik11es** [comment]
I think that there should be at least two ways of communicating.

> I believe the universal way to interact with other languages would be some sort of HTTP interface. It might be possible to have an Agent in Huginn that once the endpoint is configured shows the Agent description, validates the options and runs the Agent by making HTTP calls to the "agent server" that is written in a different language and is deployed somewhere (docker, locally, openfass, labda).

One of them you exposed perfectly right here. But there should be another way of doing this in the same machine. Take a look to https://capnproto.org/
If we develop some kind of RPC protocol there's no need to aggregate every interpreter in the world to the builds.
The user should if working inside the same machine use this protocol after installing everything needed for their reference language. If outside the machine just use HTTP protocol.

**Comment by alrik11es** [comment]
So lets imagine this HTTP API:

Somewhere in Huginn you define a new HTTP Agent and sets the URL.
After setting the URL a GET `somewhere.com/my-agent/get-info` will be done to that URL, and will return:
- A definition of the agent (Name, description ...)
- A definition of GUI for that agent in XML that will be drawn for users in Huginn.

After saving the agent. The event flow will:
Send a request to the agent POST `somewhere.com/my-agent/run` and the response be parsed by huginn in order to get the new event.

If visualizations are needed in the show option of the agent then you could add another URL that get this kind of visualizations.

What do you think?

**Comment by 0xdevalias** [comment]
My /2c is that in trying to ‘invent’/imagine this new protocol, you’re basically duplicating a lot of the work that has already been done in IMO much more active (and this more maintained) projects. I think the issue of not wanting to have to setup/interact with/learn another system are pretty minor compared to the dev costs of building that same system again (similar thoughts for translating an existing system from one language to another.. but that’s just my personal /2c)

Have a look at the API OpenFaaS uses, and perhaps the interfaces there. A lot of thought and work has gone into designing around basically exactly this problem (how can I make a small piece of language independent code run my thing). Huginn calls it an agent. OpenFaaS calls it a function. But they are practically identical in function.


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by alrik11es** [comment]
Ok ok I'm going to try OpenFaaS if you all guys say that is what I need I trust you. I don't want to reinvent the wheel obviously. If the wheel that you guys suggest work easily over a cheap vps I'm ok with that. Let me learn and try to work with this over the next few days to have a real opinion based in something real.

**Comment by alrik11es** [comment]
I've been testing Open FaaS from this morning. Wow, it is really easy to setup on my shabby VPS server. It works flawlessly with PHP so I'm really happy with it.
With solutions like this then this protocol interface is clearly not needed.
The only complain that I have with Open FaaS is that the interface is awful as hell and faulty of options... but I will survive with it anyways.

Thanks guys.

**Comment by 0xdevalias** [comment]
I don't really have the capacity to explore/implement it right now.. (maybe one day..) but my feeling is that it wouldn't be all that hard to create an OpenFasS Huginn Agent, to allow it to easily be plugged into Huginn workflows, and then everyone could easily get the best of both worlds!

**Comment by alrik11es** [comment]
Maybe by writing the .yml and create a function inside somewhat called "functions" directory trough the API and the file system. And redirecting the events through HTTP. I mean with Huginn and a UI interface that allows the user to create new functions including the source and the ability to build and deploy.
The OpenFaaS API does not allow to create a function with code so you need to create the code first on the server. Or at least that's what I've found until now.

I think that I would be more than happy with something that fixes that.

It really seems not so hard for me to implement that in PHP instead of continuing porting huginn. Which really is itself a project that I've started just for fun sometime ago. And this should be simpler and useful than a huginn port to PHP.

**Comment by 0xdevalias** [comment]
@alrik11es If you follow the link I pasted above through to http://editor.swagger.io/ and import the swagger URL provided (on my link above), you can see  that a new function can be deployed with `POST` `/system/functions`.

OpenFaaS is built around docker containers, so you're basically telling it where to get the pre-made function docker container from.

----

Though when I said "create an OpenFasS Huginn Agent" above, I meant implementing the OpenFaaS API on the Huginn side. Initially I wouldn't even care so much about deploying new functions, the tools in OpenFaaS (WebUI, CLI, etc) are already perfectly good at that. The thing I would see value in implementing is the ability for Huginn to invoke OpenFaaS functions, and retrieve the result.

The swagger docs linked above show that this would be done with `POST` `/function/{functionName}` or `POST` `/async-function/{functionName}` (though for the latter, [you would need to have a 'webhook' style receiver in Huginn to get the result](https://docs.openfaas.com/reference/async/#how-it-works) I believe). So basically you could already connect these really easily using the Huginn Web Agent.

Where I would see more value in a 'deeper' integration is to automate some of the setup/selection of functions. For example, you could use `GET` `/system/functions` and `GET` `/system/function/{functionName}` to list the available OpenFaaS functions/details about them, and then build some UI showing them within Huginn as 'external agents'. You could connect Huginn's concept of secrets with OpenFaaS's concept of secrets, managed by the `/system/secrets` API endpoint.

Those are the sorts of things I envisage when I think about a Huginn/OpenFaaS integration.

**Comment by alrik11es** [comment]
I'm a little embarrassed of not expressing myself perfectly. Sometimes expressing myself correctly in English is really difficult for me. It happens sometimes to me in Spanish which is my native language so...

> The swagger docs linked above show that this would be done with POST /function/{functionName} or POST /async-function/{functionName} (though for the latter, [you would need to have a webhook agent in Huginn to get the result](https://docs.openfaas.com/reference/async/#how-it-works) I believe). So basically you could already connect these really easily using the Huginn Web Agent.

Yes it works like that, I've tested it.

```json
{
  "service": "nodeinfo",
  "network": "func_functions",
  "image": "functions/nodeinfo:latest",
  "envProcess": "node main.js",
  "envVars": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  },
  "constraints": [
    "node.platform.os == linux"
  ],
  "labels": {
    "foo": "bar"
  },
  "annotations": {
    "topics": "awesome-kafka-topic",
    "foo": "bar"
  },
  "secrets": [
    "secret-name-1"
  ],
  "registryAuth": "dXNlcjpwYXNzd29yZA==",
  "limits": {
    "memory": "128M",
    "cpu": "0.01"
  },
  "requests": {
    "memory": "128M",
    "cpu": "0.01"
  },
  "readOnlyRootFilesystem": true
}
```
`POST /system/functions` until what I've seen this request do not allow creating new code but it does push existent from a docker registry.

When I talked like in my other comment I though like if I were implementing this kind of technologies for my company's agnostic users. They are no ops, not even specialist developers. So this people are in the need of something that makes their lives easier not over complicate it. Of course you can connect through CLI and create a new function and so on. But I don't want my users have the need to. It's a matter of efficiency. What is efficient for them is efficient for me as well.

So your latest answer is a good opinion and I respect it and I agree mostly with it. But in my opinion the value is having everything that allows someone to create new agents/functions or whatever condensed in the same place or at least in the same application.

It's a matter of different way of thinking. Just my opinion. Not trying to deny other opinions or solutions.

Anyways I have to really thank you for pointing me towards new architectures that really makes my life easier. I'm really up into implementing this for lots of minor tasks on my company when I arrive on Monday. Thank you very much.

**Comment by virtadpt** [comment]
I've been playing around a little with OpenFaaS, and I think a couple of POST Agents would be ideal for triggering functions (though probably not writing functions).  POST Agent would also be ideal for triggering the OpenFaaS API rail for updating its local directory of ready-to-run function images.

**Comment by chrigi** [comment]
How active is this project? It seems like a lot of Pull Requests and Issues have amassed so I was wondering if Huginn is still being maintained or even developed further. What's the plan?

**Comment by dsander** [comment]
Huginn is OSS, everyone is welcome to contribute. As far as I know all pull requests that are still open are either stale because requested changes were not made or never got to a merge able state because of disagreements. 

I don't think we ever had a collaborative plan for Huginn. Contributors added the features and Agents (for that we now have [huginn-agent](https://github.com/huginn/huginn_agent)) they wanted/needed.

**Comment by chrigi** [comment]
That is absolutely fine I and I didn't want to put any pressure/blame on regular contributors. The way it currently _looks_ to me when I see the issue and PR count as well as created/updated dates on issues/milestones is that Huginn does not get much attention anymore.

If so many pull requests and issues are stale it would benefit the project (imho) to close these if they are old. I've seen there are already quite a few labels setup as well and even very well made milestones but they seem to have been unused for the last 2-3 years.

I think a good cleanup of all the old/stale issues & PRs (& milestones) as well as triaging what remains with labels & milestones would make it a lot clearer what is being worked on and what is going on with the project. Maybe even creating isse & PR templates (and a stale bot) could help organize this for the future.

**Comment by pkrolkgp** [comment]
It would be nice if we can have some translation service, so anyone can contibute with translations.

**Comment by smithjoelt** [comment]
Is this issue currently being worked on? Should we close it?

**Comment by cantino** [comment]
I am not pursuing this at the moment. It was more of a vision statement.

**Comment by smithjoelt** [comment]
Thanks. Just running some triage and wanting to close up old issues. 🙂

**Comment by ohingardail** [comment]
On the subject of the future of Huginn; it appears that the current version of Huginn doesn't work on the latest version of Ubuntu (v22.04). There's no reason why it should; the Huginn installation notes only specify [Ubuntus v14 and v18 as pre-requisites](https://github.com/huginn/huginn/blob/master/doc/manual/requirements.md).

Even so, I have managed to get Huginn running on Ubuntus v20 and v21 without too much problem.

One reason appears why Ubuntu v22 doesn't play well with Huginn is that the elderly versions of Ruby that Huginn relies on mandatorily require OpenSSL v1, and Ubuntu v22.04 installs OpenSSL v3. Downgrading OpenSSL, or reconfiguring Ruby v2.6.9 to support OpenSSL v3 (or possibly some version of LibreSSL) is a fiddly task with potential security issues that complicates future upgrade paths; it's not a goer for most users, and I would be disinclined to try it if I wanted a reliable instance of Huginn. And then there may be other problems as Huginn and its pre-requisites become increasingly aged...

Ubuntu v21 was an interim release that's been EOL'ed; there are no further updates to it, and you can't install a new instance of Ubuntu v21 because the installer can't find said updates, and you wouldn't be able to install Huginn OS pre-requisites on it anyway.

This leaves Ubuntu v20.04 LTS as the longest-lived option known to work with Huginn which will receive [maintenance updates until 2025, and security updates until 2030](https://ubuntu.com/about/release-cycle). Ubuntu v18.04, the latest version specified as [supported by Huginn](https://github.com/huginn/huginn/blob/master/doc/manual/requirements.md) will have maintenance updates until 2023 and security updates until 2028.

**Comment by 0xdevalias** [comment]
@ohingardail That seems like something that would be worth a new issue for for visibility/tracking, as I suspect it will get lost/buried away tacked onto the end of this now closed issue.

**Comment by ohingardail** [comment]
Acknowledged. I wasn't sure how important this Ubuntu EOL issue was, since it's some way off and there may be technical details and mitigations the community knows about that I don't. However, a new issue report may be the best way to find out!

**Comment by virtadpt** [comment]
> On the subject of the future of Huginn; it appears that the current version of Huginn doesn't work on the latest version of Ubuntu (v22.04). There's no reason why it should; the Huginn installation notes only specify [Ubuntus v14 and v18 as supported](https://github.com/huginn/huginn/blob/master/doc/manual/requirements.md).

I'm running Huginn on Ubuntu Server 22.04 LTS and have been since a month after it came out.  One thing I'm doing is using Ruby installed with rvm, not the Ubuntu Ruby packages.
